language: scala
scala:
  - "2.10.4"
  - "2.11.5"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.ivy2/cache
script: "sbt clean coverage test"
after_success: "sbt coveralls"
